/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppProveedoresRouteImport } from './routes/_app.proveedores'
import { Route as AppProductosRouteImport } from './routes/_app.productos'
import { Route as AppPosRouteImport } from './routes/_app.pos'
import { Route as AppLotesRouteImport } from './routes/_app.lotes'
import { Route as AppKardexRouteImport } from './routes/_app.kardex'
import { Route as AppInventarioRouteImport } from './routes/_app.inventario'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClientesRouteImport } from './routes/_app.clientes'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProveedoresRoute = AppProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => AppRoute,
} as any)
const AppProductosRoute = AppProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AppRoute,
} as any)
const AppPosRoute = AppPosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => AppRoute,
} as any)
const AppLotesRoute = AppLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => AppRoute,
} as any)
const AppKardexRoute = AppKardexRouteImport.update({
  id: '/kardex',
  path: '/kardex',
  getParentRoute: () => AppRoute,
} as any)
const AppInventarioRoute = AppInventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClientesRoute = AppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventario': typeof AppInventarioRoute
  '/kardex': typeof AppKardexRoute
  '/lotes': typeof AppLotesRoute
  '/pos': typeof AppPosRoute
  '/productos': typeof AppProductosRoute
  '/proveedores': typeof AppProveedoresRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/categorias': typeof AppCategoriasRoute
  '/clientes': typeof AppClientesRoute
  '/dashboard': typeof AppDashboardRoute
  '/inventario': typeof AppInventarioRoute
  '/kardex': typeof AppKardexRoute
  '/lotes': typeof AppLotesRoute
  '/pos': typeof AppPosRoute
  '/productos': typeof AppProductosRoute
  '/proveedores': typeof AppProveedoresRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/clientes': typeof AppClientesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inventario': typeof AppInventarioRoute
  '/_app/kardex': typeof AppKardexRoute
  '/_app/lotes': typeof AppLotesRoute
  '/_app/pos': typeof AppPosRoute
  '/_app/productos': typeof AppProductosRoute
  '/_app/proveedores': typeof AppProveedoresRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/categorias'
    | '/clientes'
    | '/dashboard'
    | '/inventario'
    | '/kardex'
    | '/lotes'
    | '/pos'
    | '/productos'
    | '/proveedores'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/categorias'
    | '/clientes'
    | '/dashboard'
    | '/inventario'
    | '/kardex'
    | '/lotes'
    | '/pos'
    | '/productos'
    | '/proveedores'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/categorias'
    | '/_app/clientes'
    | '/_app/dashboard'
    | '/_app/inventario'
    | '/_app/kardex'
    | '/_app/lotes'
    | '/_app/pos'
    | '/_app/productos'
    | '/_app/proveedores'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/proveedores': {
      id: '/_app/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof AppProveedoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/productos': {
      id: '/_app/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof AppProductosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pos': {
      id: '/_app/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof AppPosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lotes': {
      id: '/_app/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof AppLotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/kardex': {
      id: '/_app/kardex'
      path: '/kardex'
      fullPath: '/kardex'
      preLoaderRoute: typeof AppKardexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventario': {
      id: '/_app/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof AppInventarioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/clientes': {
      id: '/_app/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AppClientesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppClientesRoute: typeof AppClientesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppInventarioRoute: typeof AppInventarioRoute
  AppKardexRoute: typeof AppKardexRoute
  AppLotesRoute: typeof AppLotesRoute
  AppPosRoute: typeof AppPosRoute
  AppProductosRoute: typeof AppProductosRoute
  AppProveedoresRoute: typeof AppProveedoresRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppClientesRoute: AppClientesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppInventarioRoute: AppInventarioRoute,
  AppKardexRoute: AppKardexRoute,
  AppLotesRoute: AppLotesRoute,
  AppPosRoute: AppPosRoute,
  AppProductosRoute: AppProductosRoute,
  AppProveedoresRoute: AppProveedoresRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
